a)

batch apex implements annual revenue(){

    if(Annual Revenue ≥ 10,000,000){

        System.debug(' Enterprise');
    }
    else if(Annual Revenue ≥ 1,000,000 and < 10,000,000){

        System.debug('Medium');
    }
    else{

        System.debug('Small');
    }
}

b)




c)batch scope size determines how many data should be processesd and it is directly connected with governor limits.

d)state should be implemented in this process.

